/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BlogTagTagRouteImport } from './routes/blog/tag.$tag'
import { Route as AdminPostsNewRouteImport } from './routes/admin/posts/new'
import { Route as AdminPostsIdEditRouteImport } from './routes/admin/posts/$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTagTagRoute = BlogTagTagRouteImport.update({
  id: '/blog/tag/$tag',
  path: '/blog/tag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsIdEditRoute = AdminPostsIdEditRouteImport.update({
  id: '/posts/$id/edit',
  path: '/posts/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/posts/new'
    | '/blog/tag/$tag'
    | '/admin/posts/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/blog/$slug'
    | '/admin'
    | '/blog'
    | '/admin/posts/new'
    | '/blog/tag/$tag'
    | '/admin/posts/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/blog/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/posts/new'
    | '/blog/tag/$tag'
    | '/admin/posts/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogTagTagRoute: typeof BlogTagTagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tag/$tag': {
      id: '/blog/tag/$tag'
      path: '/blog/tag/$tag'
      fullPath: '/blog/tag/$tag'
      preLoaderRoute: typeof BlogTagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/$id/edit': {
      id: '/admin/posts/$id/edit'
      path: '/posts/$id/edit'
      fullPath: '/admin/posts/$id/edit'
      preLoaderRoute: typeof AdminPostsIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsIdEditRoute: typeof AdminPostsIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsIdEditRoute: AdminPostsIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogTagTagRoute: BlogTagTagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
